Vagrant.configure("2") do |config|
    config.vm.provision :ansible, :playbook => "playbook.yml"
    config.ssh.forward_agent = true

    config.vm.provider :virtualbox do |vb, override|
        override.vm.box = "precise64"
        override.vm.box_url = "http://files.vagrantup.com/precise64.box"
    end

    config.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
        aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

        aws.ami = "ami-e7582d8e"
        aws.region = "us-east-1"
        aws.instance_type = "t1.micro"
        aws.elastic_ip = true
        aws.ssh_host_attribute = "dns_name"

        aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
        aws.security_groups = ENV['AWS_SECURITY_GROUPS']
        aws.subnet_id = ENV['AWS_SUBNET_ID']

        override.vm.box = "dummy"
        override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY_PATH']
    end
end
