Vagrant.configure("2") do |config|
	config.vm.box =  "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.ssh.forward_agent = true
	config.vm.provision :ansible, :playbook => "playbook.yml"
end
