Vagrant.configure("2") do |config|
    AWS_ACCESS_KEY_ID= ENV['AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY= ENV['AWS_SECRET_ACCESS_KEY']

    config.vm.provision :ansible, :playbook => "playbook.yml"
    config.ssh.forward_agent = true

    config.vm.provider :virtualbox do |vb, override|
        override.vm.box = "precise64"
        override.vm.box_url = "http://files.vagrantup.com/precise64.box"
    end

    config.vm.provider :aws do |aws, override|
        aws.access_key_id = AWS_ACCESS_KEY_ID
        aws.secret_access_key = AWS_SECRET_ACCESS_KEY

        aws.ami = "ami-e7582d8e"
        aws.keypair_name = "vagrant"
        aws.security_groups = ["vagrant"]

        override.vm.box = "dummy"
        override.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = "vagrant.pem"
    end
end
